django_keras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movie_review/', include('movie_review.urls')),
]

movie_review/urls.py
from django.urls import path
from . import views

app_name = 'movie_review'

urlpatterns = [
    path('', views.index, name='index'),
]

movie_review/models.py
from django.db import models

# Create your models here.

movie_review/views.py
from django.shortcuts import render
from django.http import  HttpResponse
import tensorflow as td
from tensorflow import keras
import numpy as np

data = keras.datasets.imdb
word_index = data.get_word_index()

def review_encode(s):
    #1 means 'start line'
    encoded = [1]

    for word in s:
         #translate human words to machine digits
        if word.lower() in word_index:
            encoded.append(word_index[word.lower()])
        else:
            #2 means 'word not found in dictionary'
            encoded.append(2)

    return encoded

def index(request):
    p = ''
    w = ''
    model = keras.models.load_model('model.h5')
    # assume review is either negative or positive
    class_names = ['negative', 'positive']
    try:
        review_posted = request.POST['review']
    except Exception:
        pass
    else:
        nline = review_posted.replace(',', '').replace('(', '').replace(')', '').replace(':', '')\
            .replace("\"",'').strip().split(' ')
        encode = review_encode(nline)
        encode = keras.preprocessing.sequence.pad_sequences([encode], value=0, padding='post', maxlen=256)
        w = encode
        predict = model.predict(encode)
        print(review_posted)
        print(encode)
        result = class_names[int(round(predict[0][0]))]
        p = str(predict[0][0]) + ' ' + result
        print(predict[0], result)

    return render(request, 'index.html', {'prediction': p, 'wordMap': w})

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie Review</title>
</head>
<body>
    <h2>Predict whether movie review is positive or negative</h2>

    <form action="{% url 'movie_review:index'  %}" method="post">
        {% csrf_token %}
        <label>Copy and paste movie review in English to the box below</label><br/>
        <textarea rows="8" cols="50" name='review'></textarea><br/>
        <input type="submit" value="Predict"><br/><br/>
    </form>

    <label>Prediction (0 = most negative, 1 = most positive)</label><br/>
    {{prediction}}<br/><br/>

    <label>AI word mapping, (AI dictionary contains 88584 vocabulary). extra long reviews will be trimmed for prediction</label><br/>
    {{wordMap}}
</body>
</html>